### ISSUE TITLE
Wrong CFG for microc's stmts

### ISSUE THREAD

**Issue by nicdard** [lillo/compiler-course-unipi#1]
The README.md of microc-parsing folder contains a CFG for the language. 
The rule for Stmt uses Block as body blocks for FOR and WHILE stmts. However, standard C and some tests contained within the project allow a single Stmt in place of a Block.

Below is the correct rule:

```
Stmt ::= "return" Expr ";" | Expr ";" | Block | "while" "(" Expr ")" Stmt 
        |    "for" "(" Expr? ";" Expr? ";" Expr? ")" Stmt
        |    "if" "(" Expr ")" Stmt "else" Stmt  | "if" "(" Expr ")" Stmt
```

**Comment by lillo** [comment]
Yes, they're definitely typos. Thanks, I'll fix them asap.

**Comment by nicdard** [comment]
Great! :)
